public enum UiPanelType
{
    None,
    MainScreen,
    PopupSetting,
    PopupRate,
    PopupTutorial,
    PopupNoInternet,
    PopupNotification,
    PlayScreen,
    DemoPopup,
    DemoBottomPopup,
    DemoSidePopup,
    ScreenDemoShop,
    PopupOnlineReward,
    PopupLuckyWheel,
    PopupOfflineReward,
    PopupChestRoom,
    PopupDailyReward,
    PopupLeaderboard,
    PopupConsent,
    PopupInterAdsNotif,
    PopupPopUpShowSelection,
    PopupShowSelection,
    PopupChoseLevel,
    PopupRemoveAds,
    SdkPlaceHolder //Do not rename or re-arrange
}